### ISSUE TITLE
Firefox Doesnt Support Calendar Drop Down In New Training Session

### ISSUE THREAD

**Issue by GabrielHogan** [ZJX-ARTCC/jacksonville-issue-tracker#10]
**Describe the bug**
It appears that Nick O's Firefox browser does not show the drop down.

**Additional context**
/training/session/new

**Comment by MikeRomaa** [comment]
They work fine in my Firefox 🤷🏻‍♂️

**Comment by GabrielHogan** [comment]
Closed because issue could not be replicated.
