### ISSUE TITLE
Edit User Page

### ISSUE THREAD

**Issue by GabrielHogan** [ZJX-ARTCC/jacksonville-issue-tracker#12]
**Describe the bug**

- [x] Roles totally broken

- [x] Certifications display incorrectly (edit correctly)

- [x] LOA does not submit

**Additional context**
/profile/**CID**/edit/

**Comment by GabrielHogan** [comment]
@MikeRomaa Is there any chance you can take a look at this? Not sure how we can make the frontend for the edit roles.

**Comment by MikeRomaa** [comment]
I'll submit a PR soon™

**Comment by brinbrody** [comment]
@MikeRomaa I see your PR above: Is this completely fixed, or do we still have the LOA problem?

**Comment by MikeRomaa** [comment]
> @MikeRomaa I see your PR above: Is this completely fixed, or do we still have the LOA problem?

Haven't tried it out.

**Comment by brinbrody** [comment]
As of 12/13, this issue still exists. @GabrielHogan please work on solving or assign a Web Team member to do so.

**Comment by brinbrody** [comment]
This has been solved via some janky-ass JavaScript. Closed!
