### ISSUE TITLE
Inconsistent action on ‘Request’

### ISSUE THREAD

**Issue by drchuck59** [ZJX-ARTCC/jacksonville-issue-tracker#16]
**Describe the bug**
Request does not change to Requested
Hover not functional on touchpad

**To Reproduce**
1. On iPhone11/Safari (up o date version), sign into website 
2. Click on event (...Among Us)
3. Hover thumb over Request to see “Click to request” (does not display)
4. Click on Jax_N_App Request

Repeat steps 3 and 4 with MCO_E_Twr and function normal.

**Expected behavior**
With thumb above link, “Click to request” should display. 
With thumb touching Request, should change to Requested

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  iPhone11
 - OS: iOS 14
 - Browser safari
 - Version unsure (most recent)

**Additional context**

**Comment by MikeRomaa** [comment]
I just tried it on my phone and everything works as expected, none of them show a tooltip when you "hover" over it but they they do if you click on them to request/unrequest. That's just a limitation of mobile devices.

**Comment by GabrielHogan** [comment]
Sorry, Issue was found to be Large font size on iPhone cutting off the tooltip. Works when landscape. I think if this becomes a major issue we can take a look a t restyling the page. I'm going to close the issue for now.
