### ISSUE TITLE
Manually assigning event positions bug

### ISSUE THREAD

**Issue by MGrooms792** [ZJX-ARTCC/jacksonville-issue-tracker#18]
**Describe the bug**
When manually assigning a user to an event position, that controller is not displayed until the event is saved

**To Reproduce**
1. Go to any active event
2. Click on edit event, click on a position, click manually assign user, assign a controller

**Expected behavior**
After manually assigning a user  it should show the user without having to click "save changes" just like it already does for assigning controllers that requested a position

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Additional context**

**Comment by GabrielHogan** [comment]
I was able to reproduce the bug on the production server but not on my local dev server. Requires further investigation on the production server.

**Comment by GabrielHogan** [comment]
I believe this likely was fixed when we fixed logouts. @MGrooms792 are you able to reproduce this issue on the production server at this time?

**Comment by MGrooms792** [comment]
@GabrielHogan I was able to reproduce this issue on the "Gulf Coast FNO". I manually assigned myself a position from the dropdown and I did not notice I was assigned until I hate save changes -> went back to "edit event" again, then saw my name

**Comment by brinbrody** [comment]
Resolved.
