### ISSUE TITLE
conflicting controller time indications between landing page and profile page

### ISSUE THREAD

**Issue by mtkft** [ZJX-ARTCC/jacksonville-issue-tracker#19]
zjxartcc.org landing page shows zero for the month whereas profile shows sane time.
My screenshots:
[landing](https://cdn.discordapp.com/attachments/470058732454281219/782663124057980938/unknown.png)
[profile](https://cdn.discordapp.com/attachments/470058732454281219/782663135190319114/unknown.png)
Michael Burke's:
[landing](https://cdn.discordapp.com/attachments/782744125766238248/782744340719861811/unknown.png)
[profile](https://cdn.discordapp.com/attachments/782744125766238248/782744226621816842/unknown.png)

**Comment by MikeRomaa** [comment]
Cannot reproduce. More information needed.

**Comment by brinbrody** [comment]
This has been resolved.
