### ISSUE TITLE
Statistics Page: Does not correctly display by quarter

### ISSUE THREAD

**Issue by brinbrody** [ZJX-ARTCC/jacksonville-issue-tracker#22]
**Describe the bug**
The current statistics page displays a blank month, followed by the first two months of a quarter, rather than displaying all three months.

**To Reproduce**
1. Go to 'https://www.zjxartcc.org/statistics/'
2. See error

**Expected behavior**
The three months of the current quarter should be displayed sequentially.

**Screenshots**
![image](https://user-images.githubusercontent.com/13721981/106477080-609c4900-646d-11eb-8e52-dfeadbf943c2.png)

**Comment by mtkft** [comment]
Offending line is probably /apps/api/views.py:28
```
months = [calendar.month_name[now.month - 2], calendar.month_name[now.month - 1], calendar.month_name[now.month]]
```
If months have integer indices (ideally 0 to 11) you could structure this as months `now.month %3, now.month %3 +1, now.month %3 +2` but I don't know if such indices exist.

**edit**: those are the indices for the months in the quarter, don't replace the line wholesale. For some sort of `listofmonths` you could use those as indices to point to
