### ISSUE TITLE
Preferred Routes Database

### ISSUE THREAD

**Issue by brinbrody** [ZJX-ARTCC/jacksonville-issue-tracker#8]
[ZNY PRD](https://nyartcc.org/prd/) for reference.

Database should contain all ZJX-included coded routes **and** any internal routes we generate (start with coded - custom routes can be added later).

**Comment by brinbrody** [comment]
This will replace the Flightaware link.

**Comment by GabrielHogan** [comment]
Database models implemented. Basic json API view also available for external use. Pending data from ARTCC Senior Staff.

**Comment by brinbrody** [comment]
[ZJX Preferred Routes](https://drive.google.com/file/d/1z9z36xBwwEVU7NjEFQVeBYx-JFsFSP3d/view?usp=sharing) to be added to the database.
